#Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/advancedconfig.yml

per-world-playerlist: false
allow-pwp-bypass-permission: false
ignore-pwp-in-worlds:
 - ignoredworld
 - spawn
sort-players-by-permissions: false
fix-pet-names: false
use-primary-group: true
primary-group-finding-list:
  - Owner
  - Admin
  - Helper
  - default
bukkit-bridge-mode: false
assign-groups-by-permissions: false