# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

global-playerlist:
  enabled: false
  display-others-as-spectators: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - lobby1
      - lobby2
    group2:
      - server1
      - server2

nametag-refresh-interval-milliseconds: 1000
tablist-refresh-interval-milliseconds: 1000
header-footer-refresh-interval-milliseconds: 100

header:
  - "&3&lServer name"
  - "&6&lRank: %rank%"
  - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
  - "&7Online players: &f%online%"
  - "&6Online staff: &e%staffonline%"
  - ""
  - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
  - "%animation:MyAnimation1%"
footer:
  - "%animation:MyAnimation1%"
  - "%animation:time%"
  - ""
  - "&7Visit our webpage %animation:web%"
  
tablist-objective-value: "%ping%"
group-sorting-priority-list:
  - owner
  - admin
  - mod
  - helper
  - builder
  - premium
  - player
  - default
Groups:
  Owner:
    tabprefix: "&0&l[&a&lOwner&0&l] &a"
    tagprefix: "&2&lOwner &a"
  Admin:
    tabprefix: "&0&l[&4&lAdmin&0&l] &1"
    tagprefix: "%animation:admin_prefix%"
  Player:
    tabprefix: "&0&l[&7&lPlayer&0&l] &3"
    tagprefix: "&2&lPlayer &3"
  example_group:
    header:
      - "This is an example of per-group header/footer"
    footer:
      - "applied to a group"
  _OTHER_:
    tabprefix: "%rank% "
    tagprefix: "%rank% "

Users:
  _NEZNAMY_:
    tabprefix: "&6&lTAB Author &a"
    tagprefix: "&6&lTAB &r&a"
belowname:
  enabled: true
  refresh-interval-milliseconds: 200
  number: "%ping%"
  text: "&aPing"

enable-collision: true
revert-collision-rule-in-worlds:
  - revertedworld
do-not-move-spectators: false
per-server-settings:
  server1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
  server2-server3:
    header:
      - "This is a shared header for"
      - "server2 and server3"
placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  remove-strings:
    - "[]"
    - "< >"
server-aliases:
  hub: "&eHub"
  survival: "&bSurvival"
  plot: "&cPlot"
  
rank-aliases:
  Admin: "&4&lADMIN"
  Mod: "&b&lMOD"
  Premium: "&6&lPREMIUM"
  Ultra: "&b&lULTRA"
  Legend: "&a&lLEGEND"
  Titan: "&c&lTITAN"
  Youtuber: "&c&lYOUTUBE"
  _OTHER_: "&7No Rank"
  
disable-features-in-servers:
  header-footer:
    - disabledserver
  tablist-names:
    - disabledserver
  nametag:
    - disabledserver
  tablist-objective:
    - disabledserver
  bossbar:
    - disabledserver
  belowname:
    - disabledserver
