change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

nametag-refresh-interval-milliseconds: 1000
tablist-refresh-interval-milliseconds: 1000
header-footer-refresh-interval-milliseconds: 100

header:
  - "%animation:ServerName%"
  - "&6&lRank: %rank%"
  - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
  - "&7Online players: &f%online%"
  - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
  - ""
  - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
  - "%animation:MyAnimation1%"
footer:
  - "%animation:MyAnimation1%"
  - ""
  - "%animation:vote%"
  - ""
  - "%animation:time%"
  - ""
  - "&7Visit our webpage %animation:web%"
  
#the yellow number in tablist
#set to "" to disable
tablist-objective-value: "%ping%"

#NOT case sensitive
group-sorting-priority-list:
  - "Owner"
  - "Admin"
  - "Mod"
  - "Helper"
  - "Builder"
  - "Premium"
  - "Player"
  - "default"

#properties: tabprefix, tabsuffix, tagprefix (in name tag), tagsuffix, customtabname (modifying the name itself), header, footer
Groups:
  Owner:
    tabprefix: "&0&l[&a&lOwner&0&l] &a"
    tagprefix: "&2&lOwner &a"
    header:
      - "ur server man"
    footer:
      - "welcome"
  Admin:
    tabprefix: "&0&l[&4&lAdmin&0&l] &1"
    tagprefix: "%animation:admin_prefix%"
  Player:
    tabprefix: "&0&l[&7&lPlayer&0&l] &3"
    tagprefix: "&2&lPlayer &3"
    
  #any other group not defined above
  _OTHER_:
    tabprefix: "%rank% "
    tagprefix: "%rank% "
    tabsuffix: ""
    tagsuffix: ""

#personal settings, override group settings
Users:
  _NEZNAMY_:
    tabprefix: "&6&lTAB Author &a"
    tagprefix: "&6&lTAB &r&a"

#the vanilla belowname feature
#doesn't support player placeholders (rank, prefix), only server placeholders (time, date, animations) and static text
belowname:
  enabled: true
  refresh-interval: 200
  number: "%ping%"
  text: "&aPing"

#players 1.9+
enable-collision: true

#preventing players in spectator gamemode from appearing at the bottom of tablist with transparent name FOR OTHER PLAYERS
do-not-move-spectators: false
 
#list of worlds with different settings than default, other worlds will use settings from above
per-server-settings:
  server1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
  server2-server3:
    header:
      - "This is a shared header for"
      - "server2 and server3"
  paintball:
    header:
      - "Welcome to paintball"
    footer:
      - "Good luck!"
  lobby:
    header:
      - "Welcome to our network!"
    footer:
      - "Choose a minigame and start playing!"

#setting output of some placeholders        
placeholders:
  # %date%
  date-format: "dd.MM.yyyy"
  # %time%, pick one of these formats
  time-format: "[HH:mm:ss / h:mm a]"
  
  #if time doesn't show correctly, you can change the time it shows
  #setting to -1 will make it show 1 hours less than it does currently, 1 makes it show one hour more than currently, 0 does nothing
  time-offset: 0
  
#better showing of %rank% value
rank-aliases:
  Admin: "&4&lADMIN"
  Mod: "&b&lMOD"
  Premium: "&6&lPREMIUM"
  Ultra: "&b&lULTRA"
  Legend: "&a&lLEGEND"
  Titan: "&c&lTITAN"
  Youtuber: "&c&lYOUTUBE"
  #any group not defined above
  _OTHER_: "&7No Rank"
  
disable-features-in-servers:
  header-footer:
    - disabledserver
  tablist-names:
    - disabledserver
  nametag:
    - disabledserver
  tablist-objective:
    - disabledserver
  bossbar:
    - disabledserver
  belowname:
    - disabledserver
