#sorting type, having premium version automatically overrides sorting options from advancedconfig (if set)
#GROUPS                  = groups from config.yml, in that order
#GROUP_PERMISSIONS       = ^, but players need tab.sort.<group> permission to be considered in that group
#TABPREFIX_A_TO_Z        = alphabetically by tabprefix property
#PLACEHOLDER_LOW_TO_HIGH = insert a numeric placeholder below, sorting from lowest value to highest
#PLACEHOLDER_HIGH_TO_LOW = ^, highest to lowest, can be used for some kind of levelling system
#PLACEHOLDER_A_TO_Z      = alphabetically by the placeholder
sorting-type: GROUPS
sorting-placeholder: "%some_level_maybe?%"

#by default, names are sorted as A-Z _ a-z
#by disabling you will make it Aa-Zz
#this also applies for everything else, such as sorting by placeholder (factions, ..)
case-sentitive-sorting: true

#list of lines with adaptive height, in that order.
#after adding a new property you can give it to someone in config just like any other properties
unlimited-nametag-mode-dynamic-lines:
  - abovename
  - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
  - belowname
  - another
  
#lines with static height. Dynamic is using 0.22 blocks per line, starting at 0. With 3 lines, they are as: 0, 0.22, 0.44
#can also be negative, but be careful when configuring value so it won't end up inside of the player
unlimited-nametag-mode-static-lines:
  myCustomLine: 0.66


##############################################
################# SCOREBOARD #################
##############################################

#for bungee mode it counts as "server" instead of "world", such as disabled in servers
scoreboard:
  enabled: false
  toggle-command: /sb
  disable-in-worlds: 
    - disabledworld
  #set to NONE to have no default scoreboard
  default-scoreboard: "MyDefaultScoreboard"
  refresh-interval-ticks: 1
  per-world:
    survival: "survival"
  
scoreboards:
  MyDefaultScoreboard:
    title: "&7&l> %animation:ServerName% &7&l<"
    lines:
      - "%animation:MyAnimation1%"
      - "&7%animation:Welcome%"
      - "&b%nick%"
      - ""
      - "&7Online Players"
      - "&b%online% &7/ &b%maxplayers%"
      - ""
      - "Money"
      - "&f%money%&a$"
      - ""
      - "&7Website"
      - "%animation:web%"
      - "&a/sb &fto turn off"
      - "%animation:MyAnimation1%"
  survival:
    title: "&7&l> %animation:ServerName% &7&l<"
    lines:
      - "%animation:MyAnimation1%"
      - "&7Welcome to"
      - "&b%world% &7world"
      - ""
      - "&7Online Players in world"
      - "&b%worldonline%"
      - ""
      - "Position"
      - "&b%xPos%&8X &b%yPos%&8Y &b%zPos%&8Z"
      - "%animation:MyAnimation1%"
#toggle messages
scoreboard-on: "&2Scorebord enabled"
scoreboard-off: "&7Scoreboard disabled"