#sorting type, having premium version automatically overrides sorting options from advancedconfig (if set)
#GROUPS                  = groups from config.yml, in that order
#GROUP_PERMISSIONS       = ^, but players need tab.sort.<group> permission to be considered in that group
#TABPREFIX_A_TO_Z        = alphabetically by tabprefix property
#PLACEHOLDER_LOW_TO_HIGH = insert a numeric placeholder below, sorting from lowest value to highest
#PLACEHOLDER_HIGH_TO_LOW = ^, highest to lowest, can be used for some kind of levelling system
#PLACEHOLDER_A_TO_Z      = alphabetically by the placeholder
#GROUPS_THEN_PLACEHOLDER_HIGH_TO_LOW = primary sorting by groups, secondary by numeric placeholder (high to low)
#GROUPS_THEN_PLACEHOLDER_LOW_TO_HIGH = primary sorting by groups, secondary by numeric placeholder (low to high)
sorting-type: GROUPS
sorting-placeholder: "%some_level_maybe?%"

#by default, names are sorted as A-Z _ a-z
#by disabling you will make it Aa-Zz
#this also applies for everything else, such as sorting by placeholder (factions, ..)
case-sentitive-sorting: true

#list of lines with adaptive height, in that order.
#after adding a new property you can give it to someone in config just like any other properties
unlimited-nametag-mode-dynamic-lines:
  - abovename
  - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
  - belowname
  - another
  
#lines with static height. Dynamic is using 0.22 blocks per line, starting at 0. With 3 lines, they are as: 0, 0.22, 0.44
#can also be negative, but be careful when configuring value so it won't end up inside of the player
unlimited-nametag-mode-static-lines:
  myCustomLine: 0.66


##############################################
################# SCOREBOARD #################
##############################################
#Limitations:
#1.8 - 1.12 clients: scoreboard title 32 characters, lines 30 characters
#1.13+ clients: no limits
#maximum 15 lines, client can't display more

#for bungee mode it counts as "server" instead of "world", such as disable in servers
scoreboard:
  enabled: false
  toggle-command: /sb
  #using 1-15 instead of 0s everywhere
  use-numbers: false
  disable-in-worlds: 
    - disabledworld
  #set to NONE to have no default scoreboard
  default-scoreboard: "scoreboard3"
  refresh-interval-ticks: 1
  per-world:
    testworld: "twscoreboard"
  
scoreboards:
  scoreboard3:
    #permission is "tab.scoreboard.<scoreboard name>", in this case tab.scoreboard.scoreboard3
    permission-required: true
    #if player is missing the permission, display a different scoreboard
    #if no other should be displayed / permission required is false, delete the line entirely
    if-permission-missing: scoreboard2
    title: "Super board"
    lines:
      - "Scoreboard for people with permission"
      - "tab.scoreboard.scoreboard3"
  scoreboard2:
    #here the permission is "tab.scoreboard.scoreboard2"
    permission-required: true
    if-permission-missing: scoreboard1
    title: "Average board"
    lines:
      - "Scoreboard for people with permission"
      - "tab.scoreboard.scoreboard2"
      - "AND MISSING tab.scoreboard.scoreboard3"
  scoreboard1:
    permission-required: false
    title: "Default"
    lines:
      - "Scoreboard for people with none of"
      - "tab.scoreboard.scoreboard3 or"
      - "tab.scoreboard.scoreboard2 "
      - "permission"
  twscoreboard:
    permission-required: false
    title: "TestWorld"
    lines:
      - "This is scoreboard for everyone in testworld world"
#toggle messages
scoreboard-on: "&2Scorebord enabled"
scoreboard-off: "&7Scoreboard disabled"