#sorting type, having premium version automatically overrides sorting options from advancedconfig (if set)
#GROUPS                  = groups from config.yml, in that order
#GROUP_PERMISSIONS       = ^, but players need tab.sort.<group> permission to be considered in that group
#TABPREFIX_A_TO_Z        = alphabetically by tabprefix property
#PLACEHOLDER_LOW_TO_HIGH = insert a numeric placeholder below, sorting from lowest value to highest
#PLACEHOLDER_HIGH_TO_LOW = ^, highest to lowest, can be used for some kind of levelling system
#PLACEHOLDER_A_TO_Z      = alphabetically by the placeholder
sorting-type: GROUPS
sorting-placeholder: "%some_level_maybe?%"

#by default, names are sorted as A-Z _ a-z
#by disabling you will make it Aa-Zz
#this also applies for everything else, such as sorting by placeholder (factions, ..)
case-sentitive-sorting: true

#list of lines with adaptive height, in that order.
#after adding a new property you can give it to someone in config just like any other properties
unlimited-nametag-mode-dynamic-lines:
  - abovename
  - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
  - belowname
  - another
  
#lines with static height. Dynamic is using 0.22 blocks per line, starting at 0. With 3 lines, they are as: 0, 0.22, 0.44
#can also be negative, but be careful when configuring value so it won't end up inside of the player
unlimited-nametag-mode-static-lines:
  myCustomLine: 0.66